on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
        working-directory: ./app/ClassLibrary1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        working-directory: ./app/ClassLibrary1
